# Generated by Django 6.0.3 on 2026-03-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(blank=True, max_length=200)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('sf_id', models.CharField(blank=True, max_length=18, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtlasAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(blank=True, max_length=18, null=True)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Awaiting', 'Awaiting'), ('Ready', 'Ready')], default='Awaiting', max_length=20)),
                ('agentforce_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.student')),
            ],
        ),
    ]
