# Generated by Django 6.0.3 on 2026-03-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_advisor_course_degreerequirement_advisorslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('source_path', models.CharField(max_length=500)),
                ('chunk_count', models.IntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
